services:
  api:
    build:
      context: ./
      target: api-dev
    ports:
      - "3000:3000"
    develop:
      watch:
        - path: ./api/src
          action: sync
          target: /app/src
        - path: ./api/package.json
          action: rebuild
    env_file:
      - ./api/.env
    environment:
      PORT: ${PORT}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      CHAT_GPT_API_KEY: ${CHAT_GPT_API_KEY}
  chatbot:
    build:
      context: ./
      target: chatbot-dev
    ports:
      - "5173:5173"
    develop:
      watch:
        - path: ./chatbot/src
          action: sync
          target: /app/src
        - path: ./chatbot/package.json
          action: rebuild

